# Generated by Django 6.0.7 on 2026-08-01 08:14

import apps.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.CharField(default=apps.base.models.generate_ulid_as_string, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('founder', 'Founder'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(default=apps.base.models.generate_ulid_as_string, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('principal_capital', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('loan_tenure_days', models.PositiveIntegerField(blank=True, null=True)),
                ('interest_rate_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('defaulter_penalty_rate_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('contribution_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('contribution_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('contribution_fine_enabled', models.BooleanField(default=False)),
                ('contribution_fine_rate_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('contribution_fine_interval_days', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
